---
all:
  vars:
    ssh_ca_dir: ~/ca
    ssh_ca_key_name: homelab_ssh_ca
    ssh_ca_key_comment: Homelab SSH CA  
    domain: home.lab
    user: tyla
  children:
    cts:
      children:
        servers:
          vars:
            host_key_name: ssh_host_rsa_key
            host_crtkey: "{{ host_key_name }}-cert.pub"
          hosts:
            server1:
              ansible_host: 10.18.34.10
            server2:
              ansible_host: 10.18.34.11
            server3:
              ansible_host: 10.18.34.12
            server4:
              ansible_host: 10.18.34.13
        clients:
          vars:
            user_key_name: id_rsa
            user_crtkey: "{{ user_key_name }}-cert.pub"
          hosts:
            client1:
              ansible_host: 10.18.34.20
            client2:
              ansible_host: 10.18.34.21

    # vms:
    #   hosts:
    #     k8s-node01:
    #       ansible_host: 10.18.34.31
    #     k8s-node02:
    #       ansible_host: 10.18.34.32
