---
all:
  vars:
    ssh_ca_dir: ~/ca
    ssh_ca_key_name: homelab_ssh_ca
    ssh_ca_key_comment: Homelab SSH CA  
    domain: home.lab
    user: tyla
  children:
    cts:
    # vms:
      children:
        servers:
          vars:
            host_key_name: ssh_host_rsa_key
            host_crtkey: "{{ host_key_name }}-cert.pub"
            # lxd_limits_cpu: "2"
            # lxd_limits_memory: "2GiB"
            # lxd_root_disk_size: "15GiB"
          hosts:
            server1:
              host_index: 10
            server2:
              host_index: 11
            server3:
              host_index: 12
            server4:
              host_index: 13
        clients:
          vars:
            user_key_name: id_rsa
            user_crtkey: "{{ user_key_name }}-cert.pub"
          hosts:
            client1:
              host_index: 20
            client2:
              host_index: 21
