---

- name: Set computed LXD config (cpu/memory limits)
  ansible.builtin.set_fact:
    _lxd_config: >-
      {{
        {'user.user-data': lookup('template', 'user-data.yml.j2')}
        | combine({'limits.cpu': lxd_limits_cpu} if lxd_limits_cpu else {})
        | combine({'limits.memory': lxd_limits_memory} if lxd_limits_memory else {})
      }}
    _lxd_devices: >-
      {{
        lxd_container_devices
        | combine({'root': {'path': '/', 'pool': lxd_storage_pool, 'type': 'disk'}
                    | combine({'size': lxd_root_disk_size} if lxd_root_disk_size else {})}
                  if lxd_storage_pool else {})
      }}

- name: Create LXD instance(s)
  community.general.lxd_container:
    name: "{{ inventory_hostname }}"
    ignore_volatile_options: true
    type: "{{ lxd_container_type | default('container') }}"
    state: started
    devices: "{{ _lxd_devices }}"
    config: "{{ _lxd_config }}"
    source:
      type: image
      mode: pull
      server: "{{ lxd_image_src }}"
      protocol: "{{ lxd_protocol }}"
      alias: "{{ lxd_image }}"
    profiles: "{{ lxd_profiles | default([]) }}"
    wait_for_ipv4_addresses: "{{ lxd_wait_for_ipv4 | default(true) }}"
    timeout: "{{ lxd_timeout | default(120) }}"

- name: Add/update localhost /etc/hosts entries for DNS name resolution
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} - Generated by Ansible role: {{ role_name }}"
    block: |
      {% for host in groups['all'] %}
      {{ hostvars[host].ansible_host | default(hostvars[host].inventory_hostname) }} {{ host }} {{ host }}.{{ domain }}
      {% endfor %}
    create: true
    mode: "0644"
  run_once: true

- name: Teardown workflow
  block:
    - name: Remove LXD instance(s)
      community.general.lxd_container:
        name: "{{ inventory_hostname }}"
        state: absent
        force_stop: true

    - name: Remove localhost /etc/hosts entries upon destroy
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "# {mark} - Generated by Ansible role: {{ role_name }}"
        state: absent
      run_once: true
  tags: [destroy, never]